config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends do
    collection do
      get :search
    end
  end
  get 'home/about'
  root 'friends#index'
  require 'sidekiq/web'
  Rails.application.routes.draw do
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true, length: { minimum: 1 }
  validates :last_name, presence: true, length: { minimum: 1}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :user_id, :numericality => {:only_integer => true}
  validates_presence_of :dob

  scope :my_friends, -> (userId) { where("user_id = ?", userId) }

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: {number_of_shards: 1 } do
    mapping dynamic: 'false' do
      indexes :first_name
      indexes :last_name
    end
  end



  def self.search(query, user)
    __elasticsearch__.search(
      {
        query: {
          bool: {
            must: {
              multi_match: {
                query: query,
                fields: ['first_name', 'last_name'],
              }
            },
            filter: {
              term: { user_id: user.id }
            }
          }
        },
        # more blocks will go IN HERE. Keep reading!
      })
  end

  #def self.search(query, filters)
  #  return Freind.__elasticsearch__.search(query, filter)
  #end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  #before_save :
  # GET /friends or /friends.json
  def index
    #@friends = Friend.all
    if(user_signed_in?)
      @friends = Friend.my_friends(current_user.id)
    end
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        #EmailWorker.perform_async(@friend, current_user)
        FriendsMailer.send_add_friend_email(@friend, current_user).deliver_later!
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    #query = params[:search_friends].presence && params[:search_friends][:query]
    if params[:query].present?
      result = Friend.search(params[:query], current_user).results.first
      if result != nil
        @friend = result._source
      end
    end

  end



  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this record" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :dob, :email, :phone, :user_id)
    end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:( t 'activerecord.attributes.friend.first_name') %>
  </div>

  <br/>
  <div class= "field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:( t 'activerecord.attributes.friend.last_name')%>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.label :dob, placeholder:( t 'activerecord.attributes.friend.dob') %>
    <%= form.date_select :dob %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :email, class:"form-control",  placeholder:( t 'activerecord.attributes.friend.email') %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control",  placeholder:( t 'activerecord.attributes.friend.phone')  %>
  </div>
  <div class="field form-group">
    <%= form.text_field :user_id,id: :friend_user_id, class:"form-control",  value:current_user.id,  type: :hidden%>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit (t 'global.menu.submit'), class:"btn btn-dark" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1><%= t 'static_pages.friend.edit.edit_friend' %></h1>

<%= render 'form', friend: @friend %>

<br/>
<%= link_to (t 'static_pages.friend.form.edit'), @friend, class:"btn btn-dark" %> |
<%= link_to (t 'global.menu.back'), friends_path, class:"btn btn-dark" %>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <p id="notice"><%= notice %></p>

  <h1><%= t 'static_pages.home.index.friend_list' %></h1>

  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th><%= t 'activerecord.attributes.friend.id' %></th>
        <th><%= t 'activerecord.attributes.friend.first_name' %></th>
        <th><%= t 'activerecord.attributes.friend.last_name' %></th>
        <th><%= t 'activerecord.attributes.friend.dob' %></th>
        <th><%= t 'activerecord.attributes.friend.email' %></th>
        <th><%= t 'activerecord.attributes.friend.phone' %></th>
        <th><%= t 'activerecord.attributes.friend.created_by' %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <td><%= friend.id %></td>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td><%= friend.dob %></td>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>
            <td><%= friend.user_id %></td>
            <td><%= link_to (t 'static_pages.friend.form.show'), friend %></td>
            <td><%= link_to (t 'static_pages.friend.form.edit'), edit_friend_path(friend) %></td>
            <td><%= link_to (t 'static_pages.friend.form.destroy'), friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to ( t 'static_pages.friend.new.add_friend'), new_friend_path, class:"btn btn-dark" %>
<% else %>
  <h1><%= t 'static_pages.home.index.hello_world' %></h1>
  <h2><%= t 'static_pages.home.index.app_desc' %></h2>
<% end %>

app/views/friends/new.html.erb
<h1><%= t 'static_pages.friend.new.add_friend' %></h1>

<%= render 'form', friend: @friend %>
<br/>
<%= link_to (t 'global.menu.back'), friends_path, class:"btn btn-dark" %>

app/views/friends/search.html.erb
<p id="notice"><%= notice %></p>
<% if @friend != nil %>
  <div class="jumbotron">
    <h1 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %> : <%= @friend.id %></h1>
    <p class="lead"><%= @friend.dob %> <br /> <%= @friend.email %> <br /> <%= @friend.phone %></p>
    <%= link_to 'Back', friends_path , class:"btn btn-dark"%>
<% else %>
  <h1> No friends exists with that name</h1>
<% end %>

</div>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %> : <%= @friend.id %></h1>
  <p class="lead"><%= @friend.dob %> <br /> <%= @friend.email %> <br /> <%= @friend.phone %></p>
  <%= link_to (t 'static_pages.friend.form.edit'), edit_friend_path(@friend), class:"btn btn-dark" %> |
  <%= link_to (t 'global.menu.back'), friends_path , class:"btn btn-dark"%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to (t 'global.menu.app'), root_path, class:"nav-link active" %>
        </li>



        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to (t 'global.menu.add_friend'), new_friend_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to (t 'global.menu.list_friends'), friends_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to (t 'global.menu.edit_profile'), edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to (t 'global.menu.about_us'), home_about_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to (t 'global.menu.sign_out'), destroy_user_session_path,method: :delete, class:"nav-link" %>
          </li>
          <%= form_tag search_friends_path, method: :get do %>
            <p>
              <%= text_field_tag :query, params[:query]%>
              <%= submit_tag (t 'global.menu.search'), name:nil,  class:"btn btn-outline-success" %>
            </p>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to (t 'global.menu.sign_up'), new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to (t 'global.menu.sign_in'), new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>



      </ul>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1><%= t 'global.menu.about_us' %></h1>

app/views/home/index.html.erb
<h1><%= t 'static_pages.home.index.hello_world' %></h1>
<h2><%= t 'static_pages.home.index.app_desc' %><</h2>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>




  <meta charset="utf-8">
  <title>Friends</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
<%= render 'home/header' %>
<br/>
<div class="container">
<%= yield %>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>